
##Data Preprocessing | IBM SkillsBuild Internship


## Import the required libraries

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import the dataset

In [46]:
df=pd.read_csv('Data.csv')

In [47]:
df.head()

Country   Age   Salary Purchased
0      India  44.0  72000.0        No
1  Thailand   27.0  48000.0       Yes
2  Indonesia  30.0  54000.0        No
3      China  38.0  61000.0        No
4      India  40.0      NaN       Yes

## Solving for missing data

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    19 non-null     object 
 1   Age        16 non-null     float64
 2   Salary     16 non-null     float64
 3   Purchased  19 non-null     object 
dtypes: float64(2), object(2)
memory usage: 736.0+ bytes


In [49]:
x=df.notnull()

In [50]:
print(x)

    Country    Age  Salary  Purchased
0      True   True    True       True
1      True   True    True       True
2      True   True    True       True
3      True   True    True       True
4      True   True   False       True
5      True   True    True       True
6      True  False    True       True
7      True   True    True       True
8      True   True    True       True
9      True   True    True       True
10     True   True   False       True
11     True   True    True       True
12     True   True    True       True
13     True  False    True       True
14     True   True    True       True
15     True  False    True       True
16     True   True   False       True
17     True   True    True       True
18     True   True    True       True


In [80]:
x=df.iloc[:,:-1]

In [81]:
y=df.iloc[:,-1]

In [82]:
print(x)

      Country   Age   Salary
0       India  44.0  72000.0
1   Thailand   27.0  48000.0
2   Indonesia  30.0  54000.0
3       China  38.0  61000.0
4       India  40.0      NaN
5       China  35.0  58000.0
6   Thailand    NaN  52000.0
7       India  48.0  79000.0
8   Indonesia  50.0  83000.0
9   Thailand   37.0  67000.0
10      India  25.0      NaN
11  Thailand   36.0  60000.0
12  Indonesia  42.0  64000.0
13      India   NaN  40000.0
14  Thailand   52.0  90000.0
15  Indonesia   NaN  55000.0
16      China  41.0      NaN
17      India  29.0  48000.0
18      China  43.0  70000.0


In [83]:
print(y)

0      No
1     Yes
2      No
3      No
4     Yes
5     Yes
6      No
7     Yes
8      No
9     Yes
10     No
11     No
12    Yes
13    Yes
14    Yes
15     No
16    Yes
17     No
18    Yes
Name: Purchased, dtype: object


In [84]:
from sklearn.impute import SimpleImputer

In [85]:
imputer = SimpleImputer(missing_values= np.nan ,strategy="mean")

In [86]:
x.iloc[:,1:3]

Age   Salary
0   44.0  72000.0
1   27.0  48000.0
2   30.0  54000.0
3   38.0  61000.0
4   40.0      NaN
5   35.0  58000.0
6    NaN  52000.0
7   48.0  79000.0
8   50.0  83000.0
9   37.0  67000.0
10  25.0      NaN
11  36.0  60000.0
12  42.0  64000.0
13   NaN  40000.0
14  52.0  90000.0
15   NaN  55000.0
16  41.0      NaN
17  29.0  48000.0
18  43.0  70000.0

In [87]:
imputer.fit(x.iloc[:,1:3])
x.iloc[:,1:3]=imputer.transform(x.iloc[:,1:3])

In [88]:
print(x)


      Country      Age   Salary
0       India  44.0000  72000.0
1   Thailand   27.0000  48000.0
2   Indonesia  30.0000  54000.0
3       China  38.0000  61000.0
4       India  40.0000  62562.5
5       China  35.0000  58000.0
6   Thailand   38.5625  52000.0
7       India  48.0000  79000.0
8   Indonesia  50.0000  83000.0
9   Thailand   37.0000  67000.0
10      India  25.0000  62562.5
11  Thailand   36.0000  60000.0
12  Indonesia  42.0000  64000.0
13      India  38.5625  40000.0
14  Thailand   52.0000  90000.0
15  Indonesia  38.5625  55000.0
16      China  41.0000  62562.5
17      India  29.0000  48000.0
18      China  43.0000  70000.0


## Encoding categorical data

In [89]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [90]:

ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [91]:
x=np.array(ct.fit_transform(x))

In [92]:
print(x)

[[0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.40000e+01 7.20000e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 2.70000e+01 4.80000e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 3.00000e+01 5.40000e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 3.80000e+01 6.10000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.00000e+01 6.25625e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 3.50000e+01 5.80000e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.85625e+01 5.20000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.80000e+01 7.90000e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 5.00000e+01 8.30000e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.70000e+01 6.70000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 2.50000e+01 6.25625e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.60000e+01 6.00000e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 4.20000e+01 6.40000e+04]
 [0.00000e+00 1.00000e+00

In [93]:
from sklearn.preprocessing import LabelEncoder

In [96]:
l=LabelEncoder()
y=l.fit_transform(y)

In [97]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [98]:
from sklearn.model_selection import train_test_split

In [108]:
X_train,X_test,Y_train,Y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [109]:
print(X_train)

[[0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 5.20000e+01 9.00000e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 4.10000e+01 6.25625e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.85625e+01 5.20000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.00000e+01 6.25625e+04]
 [0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 3.00000e+01 5.40000e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 3.50000e+01 5.80000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 3.85625e+01 4.00000e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.70000e+01 6.70000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.80000e+01 7.90000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 2.90000e+01 4.80000e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 3.60000e+01 6.00000e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 3.80000e+01 6.10000e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 4.40000e+01 7.20000e+04]
 [0.00000e+00 0.00000e+00

## Feature Scaling

In [110]:
from sklearn.preprocessing import StandardScaler

In [111]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [112]:
print(X_train)

[[-0.5        -0.70710678 -0.5         1.6583124   2.22042763  2.385368  ]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.31534835  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.1067999  -0.81477265]
 [-0.5         1.41421356 -0.5        -0.60302269  0.14215933  0.07474013]
 [-0.5        -0.70710678  2.         -0.60302269 -1.58973093 -0.6463442 ]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.7237858  -0.30948729]
 [-0.5         1.41421356 -0.5        -0.60302269 -0.1067999  -1.82534339]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.37740775  0.44844076]
 [-0.5         1.41421356 -0.5        -0.60302269  1.52767153  1.4590115 ]
 [-0.5         1.41421356 -0.5        -0.60302269 -1.76291995 -1.15162956]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.55059678 -0.14105883]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.20421873 -0.0568446 ]
 [-0.5         1.41421356 -0.5        -0.60302269  0.83491543  0.8695119 ]
 [-0.5        -0.70710678

In [113]:
print(X_test)

[[-0.5         1.41421356 -0.5        -0.60302269 -2.45567606  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -2.10929801 -1.15162956]
 [-0.5        -0.70710678  2.         -0.60302269  1.87404958  1.79586841]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.6617264   0.70108345]]


#MULTIPLE LINEAR REGRESSION

In [114]:
d=pd.read_csv('Successful_Startups.csv')

In [115]:
print(d.head())

   R&D Spend  Administration  Marketing Spend   Season     Profit
0  165349.20       136897.80        471784.10  Season1  192261.83
1  162597.70       151377.59        443898.53  Season2  191792.06
2  153441.51       101145.55        407934.54  Season3  191050.39
3  144372.41       118671.85        383199.62  Season1  182901.99
4  142107.34        91391.77        366168.42  Season3  166187.94


In [116]:
x=d.iloc[:,:-1].values

In [117]:
y=d.iloc[:,-1].values

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [124]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [125]:
reg.fit(x_train,y_train)

LinearRegression()

In [121]:

ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')

In [122]:
x=np.array(ct.fit_transform(x))

In [126]:
y_pre=reg.predict(x_test)

In [127]:
y_pre

array([103015.20159798, 132582.27760814, 132447.73845174,  71976.0985126 ,
       178537.48221049, 116161.24230162,  67851.69209677,  98791.7337469 ,
       113969.4353301 , 167921.06569546])

In [ ]:
y=reg.predict([[5]])